/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AiAgentsAmsterdamRouteImport } from './routes/ai-agents-amsterdam'
import { Route as AiAutomatiseringOpMaatRouteImport } from './routes/ai-automatisering-op-maat'
import { Route as AiConsultancyMkbRouteImport } from './routes/ai-consultancy-mkb'
import { Route as AiKlantenserviceAutomatiserenRouteImport } from './routes/ai-klantenservice-automatiseren'
import { Route as AiLeadOpvolgingRouteImport } from './routes/ai-lead-opvolging'
import { Route as AiProjectVastgelopenRouteImport } from './routes/ai-project-vastgelopen'
import { Route as AiScanRouteImport } from './routes/ai-scan'
import { Route as AiVoorHetMkbAmsterdamRouteImport } from './routes/ai-voor-het-mkb-amsterdam'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as WhatsappFollowUpAutomatiserenRouteImport } from './routes/whatsapp-follow-up-automatiseren'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated/account'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedKnowledgeRouteImport } from './routes/_authenticated/knowledge'
import { Route as BlogWaaromAiPilotsMislukkenRouteImport } from './routes/blog/waarom-ai-pilots-mislukken'
import { Route as AuthenticatedAgentsAgentIdRouteImport } from './routes/_authenticated/agents.$agentId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AiAgentsAmsterdamRoute = AiAgentsAmsterdamRouteImport.update({
  id: '/ai-agents-amsterdam',
  path: '/ai-agents-amsterdam',
  getParentRoute: () => rootRouteImport,
} as any)
const AiAutomatiseringOpMaatRoute = AiAutomatiseringOpMaatRouteImport.update({
  id: '/ai-automatisering-op-maat',
  path: '/ai-automatisering-op-maat',
  getParentRoute: () => rootRouteImport,
} as any)
const AiConsultancyMkbRoute = AiConsultancyMkbRouteImport.update({
  id: '/ai-consultancy-mkb',
  path: '/ai-consultancy-mkb',
  getParentRoute: () => rootRouteImport,
} as any)
const AiKlantenserviceAutomatiserenRoute =
  AiKlantenserviceAutomatiserenRouteImport.update({
    id: '/ai-klantenservice-automatiseren',
    path: '/ai-klantenservice-automatiseren',
    getParentRoute: () => rootRouteImport,
  } as any)
const AiLeadOpvolgingRoute = AiLeadOpvolgingRouteImport.update({
  id: '/ai-lead-opvolging',
  path: '/ai-lead-opvolging',
  getParentRoute: () => rootRouteImport,
} as any)
const AiProjectVastgelopenRoute = AiProjectVastgelopenRouteImport.update({
  id: '/ai-project-vastgelopen',
  path: '/ai-project-vastgelopen',
  getParentRoute: () => rootRouteImport,
} as any)
const AiScanRoute = AiScanRouteImport.update({
  id: '/ai-scan',
  path: '/ai-scan',
  getParentRoute: () => rootRouteImport,
} as any)
const AiVoorHetMkbAmsterdamRoute = AiVoorHetMkbAmsterdamRouteImport.update({
  id: '/ai-voor-het-mkb-amsterdam',
  path: '/ai-voor-het-mkb-amsterdam',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const WhatsappFollowUpAutomatiserenRoute =
  WhatsappFollowUpAutomatiserenRouteImport.update({
    id: '/whatsapp-follow-up-automatiseren',
    path: '/whatsapp-follow-up-automatiseren',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedKnowledgeRoute = AuthenticatedKnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const BlogWaaromAiPilotsMislukkenRoute =
  BlogWaaromAiPilotsMislukkenRouteImport.update({
    id: '/blog/waarom-ai-pilots-mislukken',
    path: '/blog/waarom-ai-pilots-mislukken',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAgentsAgentIdRoute =
  AuthenticatedAgentsAgentIdRouteImport.update({
    id: '/agents/$agentId',
    path: '/agents/$agentId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-agents-amsterdam': typeof AiAgentsAmsterdamRoute
  '/ai-automatisering-op-maat': typeof AiAutomatiseringOpMaatRoute
  '/ai-consultancy-mkb': typeof AiConsultancyMkbRoute
  '/ai-klantenservice-automatiseren': typeof AiKlantenserviceAutomatiserenRoute
  '/ai-lead-opvolging': typeof AiLeadOpvolgingRoute
  '/ai-project-vastgelopen': typeof AiProjectVastgelopenRoute
  '/ai-scan': typeof AiScanRoute
  '/ai-voor-het-mkb-amsterdam': typeof AiVoorHetMkbAmsterdamRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/whatsapp-follow-up-automatiseren': typeof WhatsappFollowUpAutomatiserenRoute
  '/account': typeof AuthenticatedAccountRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/knowledge': typeof AuthenticatedKnowledgeRoute
  '/blog/waarom-ai-pilots-mislukken': typeof BlogWaaromAiPilotsMislukkenRoute
  '/agents/$agentId': typeof AuthenticatedAgentsAgentIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-agents-amsterdam': typeof AiAgentsAmsterdamRoute
  '/ai-automatisering-op-maat': typeof AiAutomatiseringOpMaatRoute
  '/ai-consultancy-mkb': typeof AiConsultancyMkbRoute
  '/ai-klantenservice-automatiseren': typeof AiKlantenserviceAutomatiserenRoute
  '/ai-lead-opvolging': typeof AiLeadOpvolgingRoute
  '/ai-project-vastgelopen': typeof AiProjectVastgelopenRoute
  '/ai-scan': typeof AiScanRoute
  '/ai-voor-het-mkb-amsterdam': typeof AiVoorHetMkbAmsterdamRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/whatsapp-follow-up-automatiseren': typeof WhatsappFollowUpAutomatiserenRoute
  '/account': typeof AuthenticatedAccountRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/knowledge': typeof AuthenticatedKnowledgeRoute
  '/blog/waarom-ai-pilots-mislukken': typeof BlogWaaromAiPilotsMislukkenRoute
  '/agents/$agentId': typeof AuthenticatedAgentsAgentIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/ai-agents-amsterdam': typeof AiAgentsAmsterdamRoute
  '/ai-automatisering-op-maat': typeof AiAutomatiseringOpMaatRoute
  '/ai-consultancy-mkb': typeof AiConsultancyMkbRoute
  '/ai-klantenservice-automatiseren': typeof AiKlantenserviceAutomatiserenRoute
  '/ai-lead-opvolging': typeof AiLeadOpvolgingRoute
  '/ai-project-vastgelopen': typeof AiProjectVastgelopenRoute
  '/ai-scan': typeof AiScanRoute
  '/ai-voor-het-mkb-amsterdam': typeof AiVoorHetMkbAmsterdamRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/whatsapp-follow-up-automatiseren': typeof WhatsappFollowUpAutomatiserenRoute
  '/_authenticated/account': typeof AuthenticatedAccountRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/knowledge': typeof AuthenticatedKnowledgeRoute
  '/blog/waarom-ai-pilots-mislukken': typeof BlogWaaromAiPilotsMislukkenRoute
  '/_authenticated/agents/$agentId': typeof AuthenticatedAgentsAgentIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-agents-amsterdam'
    | '/ai-automatisering-op-maat'
    | '/ai-consultancy-mkb'
    | '/ai-klantenservice-automatiseren'
    | '/ai-lead-opvolging'
    | '/ai-project-vastgelopen'
    | '/ai-scan'
    | '/ai-voor-het-mkb-amsterdam'
    | '/auth'
    | '/reset-password'
    | '/whatsapp-follow-up-automatiseren'
    | '/account'
    | '/admin'
    | '/dashboard'
    | '/knowledge'
    | '/blog/waarom-ai-pilots-mislukken'
    | '/agents/$agentId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-agents-amsterdam'
    | '/ai-automatisering-op-maat'
    | '/ai-consultancy-mkb'
    | '/ai-klantenservice-automatiseren'
    | '/ai-lead-opvolging'
    | '/ai-project-vastgelopen'
    | '/ai-scan'
    | '/ai-voor-het-mkb-amsterdam'
    | '/auth'
    | '/reset-password'
    | '/whatsapp-follow-up-automatiseren'
    | '/account'
    | '/admin'
    | '/dashboard'
    | '/knowledge'
    | '/blog/waarom-ai-pilots-mislukken'
    | '/agents/$agentId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/ai-agents-amsterdam'
    | '/ai-automatisering-op-maat'
    | '/ai-consultancy-mkb'
    | '/ai-klantenservice-automatiseren'
    | '/ai-lead-opvolging'
    | '/ai-project-vastgelopen'
    | '/ai-scan'
    | '/ai-voor-het-mkb-amsterdam'
    | '/auth'
    | '/reset-password'
    | '/whatsapp-follow-up-automatiseren'
    | '/_authenticated/account'
    | '/_authenticated/admin'
    | '/_authenticated/dashboard'
    | '/_authenticated/knowledge'
    | '/blog/waarom-ai-pilots-mislukken'
    | '/_authenticated/agents/$agentId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AiAgentsAmsterdamRoute: typeof AiAgentsAmsterdamRoute
  AiAutomatiseringOpMaatRoute: typeof AiAutomatiseringOpMaatRoute
  AiConsultancyMkbRoute: typeof AiConsultancyMkbRoute
  AiKlantenserviceAutomatiserenRoute: typeof AiKlantenserviceAutomatiserenRoute
  AiLeadOpvolgingRoute: typeof AiLeadOpvolgingRoute
  AiProjectVastgelopenRoute: typeof AiProjectVastgelopenRoute
  AiScanRoute: typeof AiScanRoute
  AiVoorHetMkbAmsterdamRoute: typeof AiVoorHetMkbAmsterdamRoute
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  WhatsappFollowUpAutomatiserenRoute: typeof WhatsappFollowUpAutomatiserenRoute
  BlogWaaromAiPilotsMislukkenRoute: typeof BlogWaaromAiPilotsMislukkenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-agents-amsterdam': {
      id: '/ai-agents-amsterdam'
      path: '/ai-agents-amsterdam'
      fullPath: '/ai-agents-amsterdam'
      preLoaderRoute: typeof AiAgentsAmsterdamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-automatisering-op-maat': {
      id: '/ai-automatisering-op-maat'
      path: '/ai-automatisering-op-maat'
      fullPath: '/ai-automatisering-op-maat'
      preLoaderRoute: typeof AiAutomatiseringOpMaatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-consultancy-mkb': {
      id: '/ai-consultancy-mkb'
      path: '/ai-consultancy-mkb'
      fullPath: '/ai-consultancy-mkb'
      preLoaderRoute: typeof AiConsultancyMkbRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-klantenservice-automatiseren': {
      id: '/ai-klantenservice-automatiseren'
      path: '/ai-klantenservice-automatiseren'
      fullPath: '/ai-klantenservice-automatiseren'
      preLoaderRoute: typeof AiKlantenserviceAutomatiserenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-lead-opvolging': {
      id: '/ai-lead-opvolging'
      path: '/ai-lead-opvolging'
      fullPath: '/ai-lead-opvolging'
      preLoaderRoute: typeof AiLeadOpvolgingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-project-vastgelopen': {
      id: '/ai-project-vastgelopen'
      path: '/ai-project-vastgelopen'
      fullPath: '/ai-project-vastgelopen'
      preLoaderRoute: typeof AiProjectVastgelopenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-scan': {
      id: '/ai-scan'
      path: '/ai-scan'
      fullPath: '/ai-scan'
      preLoaderRoute: typeof AiScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-voor-het-mkb-amsterdam': {
      id: '/ai-voor-het-mkb-amsterdam'
      path: '/ai-voor-het-mkb-amsterdam'
      fullPath: '/ai-voor-het-mkb-amsterdam'
      preLoaderRoute: typeof AiVoorHetMkbAmsterdamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/whatsapp-follow-up-automatiseren': {
      id: '/whatsapp-follow-up-automatiseren'
      path: '/whatsapp-follow-up-automatiseren'
      fullPath: '/whatsapp-follow-up-automatiseren'
      preLoaderRoute: typeof WhatsappFollowUpAutomatiserenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/knowledge': {
      id: '/_authenticated/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof AuthenticatedKnowledgeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/blog/waarom-ai-pilots-mislukken': {
      id: '/blog/waarom-ai-pilots-mislukken'
      path: '/blog/waarom-ai-pilots-mislukken'
      fullPath: '/blog/waarom-ai-pilots-mislukken'
      preLoaderRoute: typeof BlogWaaromAiPilotsMislukkenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/agents/$agentId': {
      id: '/_authenticated/agents/$agentId'
      path: '/agents/$agentId'
      fullPath: '/agents/$agentId'
      preLoaderRoute: typeof AuthenticatedAgentsAgentIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRoute
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedKnowledgeRoute: typeof AuthenticatedKnowledgeRoute
  AuthenticatedAgentsAgentIdRoute: typeof AuthenticatedAgentsAgentIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAccountRoute: AuthenticatedAccountRoute,
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedKnowledgeRoute: AuthenticatedKnowledgeRoute,
  AuthenticatedAgentsAgentIdRoute: AuthenticatedAgentsAgentIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AiAgentsAmsterdamRoute: AiAgentsAmsterdamRoute,
  AiAutomatiseringOpMaatRoute: AiAutomatiseringOpMaatRoute,
  AiConsultancyMkbRoute: AiConsultancyMkbRoute,
  AiKlantenserviceAutomatiserenRoute: AiKlantenserviceAutomatiserenRoute,
  AiLeadOpvolgingRoute: AiLeadOpvolgingRoute,
  AiProjectVastgelopenRoute: AiProjectVastgelopenRoute,
  AiScanRoute: AiScanRoute,
  AiVoorHetMkbAmsterdamRoute: AiVoorHetMkbAmsterdamRoute,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  WhatsappFollowUpAutomatiserenRoute: WhatsappFollowUpAutomatiserenRoute,
  BlogWaaromAiPilotsMislukkenRoute: BlogWaaromAiPilotsMislukkenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
