/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AfmeldenRouteImport } from './routes/afmelden'
import { Route as AiAgentsAmsterdamRouteImport } from './routes/ai-agents-amsterdam'
import { Route as AiAutomatiseringOpMaatRouteImport } from './routes/ai-automatisering-op-maat'
import { Route as AiBeleidRouteImport } from './routes/ai-beleid'
import { Route as AiConsultancyMkbRouteImport } from './routes/ai-consultancy-mkb'
import { Route as AiKlantenserviceAutomatiserenRouteImport } from './routes/ai-klantenservice-automatiseren'
import { Route as AiLeadOpvolgingRouteImport } from './routes/ai-lead-opvolging'
import { Route as AiProjectVastgelopenRouteImport } from './routes/ai-project-vastgelopen'
import { Route as AiScanRouteImport } from './routes/ai-scan'
import { Route as AiVoorHetMkbAmsterdamRouteImport } from './routes/ai-voor-het-mkb-amsterdam'
import { Route as AlgemeneVoorwaardenRouteImport } from './routes/algemene-voorwaarden'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as PrivacyverklaringRouteImport } from './routes/privacyverklaring'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as TarievenRouteImport } from './routes/tarieven'
import { Route as WhatsappFollowUpAutomatiserenRouteImport } from './routes/whatsapp-follow-up-automatiseren'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated/account'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAntwoordenRouteImport } from './routes/_authenticated/antwoorden'
import { Route as AuthenticatedBerichtenRouteImport } from './routes/_authenticated/berichten'
import { Route as AuthenticatedBezorgenRouteImport } from './routes/_authenticated/bezorgen'
import { Route as AuthenticatedBezorglijstRouteImport } from './routes/_authenticated/bezorglijst'
import { Route as AuthenticatedCampagnesRouteImport } from './routes/_authenticated/campagnes'
import { Route as AuthenticatedContactenRouteImport } from './routes/_authenticated/contacten'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedKnowledgeRouteImport } from './routes/_authenticated/knowledge'
import { Route as AuthenticatedSupportRouteImport } from './routes/_authenticated/support'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as BlogWaaromAiPilotsMislukkenRouteImport } from './routes/blog/waarom-ai-pilots-mislukken'
import { Route as EmbedSlugRouteImport } from './routes/embed.$slug'
import { Route as AuthenticatedAgentsAgentIdRouteImport } from './routes/_authenticated/agents.$agentId'
import { Route as AuthenticatedContactContactIdRouteImport } from './routes/_authenticated/contact.$contactId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AfmeldenRoute = AfmeldenRouteImport.update({
  id: '/afmelden',
  path: '/afmelden',
  getParentRoute: () => rootRouteImport,
} as any)
const AiAgentsAmsterdamRoute = AiAgentsAmsterdamRouteImport.update({
  id: '/ai-agents-amsterdam',
  path: '/ai-agents-amsterdam',
  getParentRoute: () => rootRouteImport,
} as any)
const AiAutomatiseringOpMaatRoute = AiAutomatiseringOpMaatRouteImport.update({
  id: '/ai-automatisering-op-maat',
  path: '/ai-automatisering-op-maat',
  getParentRoute: () => rootRouteImport,
} as any)
const AiBeleidRoute = AiBeleidRouteImport.update({
  id: '/ai-beleid',
  path: '/ai-beleid',
  getParentRoute: () => rootRouteImport,
} as any)
const AiConsultancyMkbRoute = AiConsultancyMkbRouteImport.update({
  id: '/ai-consultancy-mkb',
  path: '/ai-consultancy-mkb',
  getParentRoute: () => rootRouteImport,
} as any)
const AiKlantenserviceAutomatiserenRoute =
  AiKlantenserviceAutomatiserenRouteImport.update({
    id: '/ai-klantenservice-automatiseren',
    path: '/ai-klantenservice-automatiseren',
    getParentRoute: () => rootRouteImport,
  } as any)
const AiLeadOpvolgingRoute = AiLeadOpvolgingRouteImport.update({
  id: '/ai-lead-opvolging',
  path: '/ai-lead-opvolging',
  getParentRoute: () => rootRouteImport,
} as any)
const AiProjectVastgelopenRoute = AiProjectVastgelopenRouteImport.update({
  id: '/ai-project-vastgelopen',
  path: '/ai-project-vastgelopen',
  getParentRoute: () => rootRouteImport,
} as any)
const AiScanRoute = AiScanRouteImport.update({
  id: '/ai-scan',
  path: '/ai-scan',
  getParentRoute: () => rootRouteImport,
} as any)
const AiVoorHetMkbAmsterdamRoute = AiVoorHetMkbAmsterdamRouteImport.update({
  id: '/ai-voor-het-mkb-amsterdam',
  path: '/ai-voor-het-mkb-amsterdam',
  getParentRoute: () => rootRouteImport,
} as any)
const AlgemeneVoorwaardenRoute = AlgemeneVoorwaardenRouteImport.update({
  id: '/algemene-voorwaarden',
  path: '/algemene-voorwaarden',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyverklaringRoute = PrivacyverklaringRouteImport.update({
  id: '/privacyverklaring',
  path: '/privacyverklaring',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const TarievenRoute = TarievenRouteImport.update({
  id: '/tarieven',
  path: '/tarieven',
  getParentRoute: () => rootRouteImport,
} as any)
const WhatsappFollowUpAutomatiserenRoute =
  WhatsappFollowUpAutomatiserenRouteImport.update({
    id: '/whatsapp-follow-up-automatiseren',
    path: '/whatsapp-follow-up-automatiseren',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAntwoordenRoute = AuthenticatedAntwoordenRouteImport.update({
  id: '/antwoorden',
  path: '/antwoorden',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBerichtenRoute = AuthenticatedBerichtenRouteImport.update({
  id: '/berichten',
  path: '/berichten',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBezorgenRoute = AuthenticatedBezorgenRouteImport.update({
  id: '/bezorgen',
  path: '/bezorgen',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBezorglijstRoute =
  AuthenticatedBezorglijstRouteImport.update({
    id: '/bezorglijst',
    path: '/bezorglijst',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCampagnesRoute = AuthenticatedCampagnesRouteImport.update({
  id: '/campagnes',
  path: '/campagnes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedContactenRoute = AuthenticatedContactenRouteImport.update({
  id: '/contacten',
  path: '/contacten',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedKnowledgeRoute = AuthenticatedKnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSupportRoute = AuthenticatedSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogWaaromAiPilotsMislukkenRoute =
  BlogWaaromAiPilotsMislukkenRouteImport.update({
    id: '/blog/waarom-ai-pilots-mislukken',
    path: '/blog/waarom-ai-pilots-mislukken',
    getParentRoute: () => rootRouteImport,
  } as any)
const EmbedSlugRoute = EmbedSlugRouteImport.update({
  id: '/embed/$slug',
  path: '/embed/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAgentsAgentIdRoute =
  AuthenticatedAgentsAgentIdRouteImport.update({
    id: '/agents/$agentId',
    path: '/agents/$agentId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedContactContactIdRoute =
  AuthenticatedContactContactIdRouteImport.update({
    id: '/contact/$contactId',
    path: '/contact/$contactId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/afmelden': typeof AfmeldenRoute
  '/ai-agents-amsterdam': typeof AiAgentsAmsterdamRoute
  '/ai-automatisering-op-maat': typeof AiAutomatiseringOpMaatRoute
  '/ai-beleid': typeof AiBeleidRoute
  '/ai-consultancy-mkb': typeof AiConsultancyMkbRoute
  '/ai-klantenservice-automatiseren': typeof AiKlantenserviceAutomatiserenRoute
  '/ai-lead-opvolging': typeof AiLeadOpvolgingRoute
  '/ai-project-vastgelopen': typeof AiProjectVastgelopenRoute
  '/ai-scan': typeof AiScanRoute
  '/ai-voor-het-mkb-amsterdam': typeof AiVoorHetMkbAmsterdamRoute
  '/algemene-voorwaarden': typeof AlgemeneVoorwaardenRoute
  '/auth': typeof AuthRoute
  '/privacyverklaring': typeof PrivacyverklaringRoute
  '/reset-password': typeof ResetPasswordRoute
  '/tarieven': typeof TarievenRoute
  '/whatsapp-follow-up-automatiseren': typeof WhatsappFollowUpAutomatiserenRoute
  '/account': typeof AuthenticatedAccountRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/antwoorden': typeof AuthenticatedAntwoordenRoute
  '/berichten': typeof AuthenticatedBerichtenRoute
  '/bezorgen': typeof AuthenticatedBezorgenRoute
  '/bezorglijst': typeof AuthenticatedBezorglijstRoute
  '/campagnes': typeof AuthenticatedCampagnesRoute
  '/contacten': typeof AuthenticatedContactenRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/knowledge': typeof AuthenticatedKnowledgeRoute
  '/support': typeof AuthenticatedSupportRoute
  '/blog/waarom-ai-pilots-mislukken': typeof BlogWaaromAiPilotsMislukkenRoute
  '/embed/$slug': typeof EmbedSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/agents/$agentId': typeof AuthenticatedAgentsAgentIdRoute
  '/contact/$contactId': typeof AuthenticatedContactContactIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/afmelden': typeof AfmeldenRoute
  '/ai-agents-amsterdam': typeof AiAgentsAmsterdamRoute
  '/ai-automatisering-op-maat': typeof AiAutomatiseringOpMaatRoute
  '/ai-beleid': typeof AiBeleidRoute
  '/ai-consultancy-mkb': typeof AiConsultancyMkbRoute
  '/ai-klantenservice-automatiseren': typeof AiKlantenserviceAutomatiserenRoute
  '/ai-lead-opvolging': typeof AiLeadOpvolgingRoute
  '/ai-project-vastgelopen': typeof AiProjectVastgelopenRoute
  '/ai-scan': typeof AiScanRoute
  '/ai-voor-het-mkb-amsterdam': typeof AiVoorHetMkbAmsterdamRoute
  '/algemene-voorwaarden': typeof AlgemeneVoorwaardenRoute
  '/auth': typeof AuthRoute
  '/privacyverklaring': typeof PrivacyverklaringRoute
  '/reset-password': typeof ResetPasswordRoute
  '/tarieven': typeof TarievenRoute
  '/whatsapp-follow-up-automatiseren': typeof WhatsappFollowUpAutomatiserenRoute
  '/account': typeof AuthenticatedAccountRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/antwoorden': typeof AuthenticatedAntwoordenRoute
  '/berichten': typeof AuthenticatedBerichtenRoute
  '/bezorgen': typeof AuthenticatedBezorgenRoute
  '/bezorglijst': typeof AuthenticatedBezorglijstRoute
  '/campagnes': typeof AuthenticatedCampagnesRoute
  '/contacten': typeof AuthenticatedContactenRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/knowledge': typeof AuthenticatedKnowledgeRoute
  '/support': typeof AuthenticatedSupportRoute
  '/blog/waarom-ai-pilots-mislukken': typeof BlogWaaromAiPilotsMislukkenRoute
  '/embed/$slug': typeof EmbedSlugRoute
  '/blog': typeof BlogIndexRoute
  '/agents/$agentId': typeof AuthenticatedAgentsAgentIdRoute
  '/contact/$contactId': typeof AuthenticatedContactContactIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/afmelden': typeof AfmeldenRoute
  '/ai-agents-amsterdam': typeof AiAgentsAmsterdamRoute
  '/ai-automatisering-op-maat': typeof AiAutomatiseringOpMaatRoute
  '/ai-beleid': typeof AiBeleidRoute
  '/ai-consultancy-mkb': typeof AiConsultancyMkbRoute
  '/ai-klantenservice-automatiseren': typeof AiKlantenserviceAutomatiserenRoute
  '/ai-lead-opvolging': typeof AiLeadOpvolgingRoute
  '/ai-project-vastgelopen': typeof AiProjectVastgelopenRoute
  '/ai-scan': typeof AiScanRoute
  '/ai-voor-het-mkb-amsterdam': typeof AiVoorHetMkbAmsterdamRoute
  '/algemene-voorwaarden': typeof AlgemeneVoorwaardenRoute
  '/auth': typeof AuthRoute
  '/privacyverklaring': typeof PrivacyverklaringRoute
  '/reset-password': typeof ResetPasswordRoute
  '/tarieven': typeof TarievenRoute
  '/whatsapp-follow-up-automatiseren': typeof WhatsappFollowUpAutomatiserenRoute
  '/_authenticated/account': typeof AuthenticatedAccountRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/antwoorden': typeof AuthenticatedAntwoordenRoute
  '/_authenticated/berichten': typeof AuthenticatedBerichtenRoute
  '/_authenticated/bezorgen': typeof AuthenticatedBezorgenRoute
  '/_authenticated/bezorglijst': typeof AuthenticatedBezorglijstRoute
  '/_authenticated/campagnes': typeof AuthenticatedCampagnesRoute
  '/_authenticated/contacten': typeof AuthenticatedContactenRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/knowledge': typeof AuthenticatedKnowledgeRoute
  '/_authenticated/support': typeof AuthenticatedSupportRoute
  '/blog/waarom-ai-pilots-mislukken': typeof BlogWaaromAiPilotsMislukkenRoute
  '/embed/$slug': typeof EmbedSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/_authenticated/agents/$agentId': typeof AuthenticatedAgentsAgentIdRoute
  '/_authenticated/contact/$contactId': typeof AuthenticatedContactContactIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/afmelden'
    | '/ai-agents-amsterdam'
    | '/ai-automatisering-op-maat'
    | '/ai-beleid'
    | '/ai-consultancy-mkb'
    | '/ai-klantenservice-automatiseren'
    | '/ai-lead-opvolging'
    | '/ai-project-vastgelopen'
    | '/ai-scan'
    | '/ai-voor-het-mkb-amsterdam'
    | '/algemene-voorwaarden'
    | '/auth'
    | '/privacyverklaring'
    | '/reset-password'
    | '/tarieven'
    | '/whatsapp-follow-up-automatiseren'
    | '/account'
    | '/admin'
    | '/antwoorden'
    | '/berichten'
    | '/bezorgen'
    | '/bezorglijst'
    | '/campagnes'
    | '/contacten'
    | '/dashboard'
    | '/knowledge'
    | '/support'
    | '/blog/waarom-ai-pilots-mislukken'
    | '/embed/$slug'
    | '/blog/'
    | '/agents/$agentId'
    | '/contact/$contactId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/afmelden'
    | '/ai-agents-amsterdam'
    | '/ai-automatisering-op-maat'
    | '/ai-beleid'
    | '/ai-consultancy-mkb'
    | '/ai-klantenservice-automatiseren'
    | '/ai-lead-opvolging'
    | '/ai-project-vastgelopen'
    | '/ai-scan'
    | '/ai-voor-het-mkb-amsterdam'
    | '/algemene-voorwaarden'
    | '/auth'
    | '/privacyverklaring'
    | '/reset-password'
    | '/tarieven'
    | '/whatsapp-follow-up-automatiseren'
    | '/account'
    | '/admin'
    | '/antwoorden'
    | '/berichten'
    | '/bezorgen'
    | '/bezorglijst'
    | '/campagnes'
    | '/contacten'
    | '/dashboard'
    | '/knowledge'
    | '/support'
    | '/blog/waarom-ai-pilots-mislukken'
    | '/embed/$slug'
    | '/blog'
    | '/agents/$agentId'
    | '/contact/$contactId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/afmelden'
    | '/ai-agents-amsterdam'
    | '/ai-automatisering-op-maat'
    | '/ai-beleid'
    | '/ai-consultancy-mkb'
    | '/ai-klantenservice-automatiseren'
    | '/ai-lead-opvolging'
    | '/ai-project-vastgelopen'
    | '/ai-scan'
    | '/ai-voor-het-mkb-amsterdam'
    | '/algemene-voorwaarden'
    | '/auth'
    | '/privacyverklaring'
    | '/reset-password'
    | '/tarieven'
    | '/whatsapp-follow-up-automatiseren'
    | '/_authenticated/account'
    | '/_authenticated/admin'
    | '/_authenticated/antwoorden'
    | '/_authenticated/berichten'
    | '/_authenticated/bezorgen'
    | '/_authenticated/bezorglijst'
    | '/_authenticated/campagnes'
    | '/_authenticated/contacten'
    | '/_authenticated/dashboard'
    | '/_authenticated/knowledge'
    | '/_authenticated/support'
    | '/blog/waarom-ai-pilots-mislukken'
    | '/embed/$slug'
    | '/blog/'
    | '/_authenticated/agents/$agentId'
    | '/_authenticated/contact/$contactId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AfmeldenRoute: typeof AfmeldenRoute
  AiAgentsAmsterdamRoute: typeof AiAgentsAmsterdamRoute
  AiAutomatiseringOpMaatRoute: typeof AiAutomatiseringOpMaatRoute
  AiBeleidRoute: typeof AiBeleidRoute
  AiConsultancyMkbRoute: typeof AiConsultancyMkbRoute
  AiKlantenserviceAutomatiserenRoute: typeof AiKlantenserviceAutomatiserenRoute
  AiLeadOpvolgingRoute: typeof AiLeadOpvolgingRoute
  AiProjectVastgelopenRoute: typeof AiProjectVastgelopenRoute
  AiScanRoute: typeof AiScanRoute
  AiVoorHetMkbAmsterdamRoute: typeof AiVoorHetMkbAmsterdamRoute
  AlgemeneVoorwaardenRoute: typeof AlgemeneVoorwaardenRoute
  AuthRoute: typeof AuthRoute
  PrivacyverklaringRoute: typeof PrivacyverklaringRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TarievenRoute: typeof TarievenRoute
  WhatsappFollowUpAutomatiserenRoute: typeof WhatsappFollowUpAutomatiserenRoute
  BlogWaaromAiPilotsMislukkenRoute: typeof BlogWaaromAiPilotsMislukkenRoute
  EmbedSlugRoute: typeof EmbedSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/afmelden': {
      id: '/afmelden'
      path: '/afmelden'
      fullPath: '/afmelden'
      preLoaderRoute: typeof AfmeldenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-agents-amsterdam': {
      id: '/ai-agents-amsterdam'
      path: '/ai-agents-amsterdam'
      fullPath: '/ai-agents-amsterdam'
      preLoaderRoute: typeof AiAgentsAmsterdamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-automatisering-op-maat': {
      id: '/ai-automatisering-op-maat'
      path: '/ai-automatisering-op-maat'
      fullPath: '/ai-automatisering-op-maat'
      preLoaderRoute: typeof AiAutomatiseringOpMaatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-beleid': {
      id: '/ai-beleid'
      path: '/ai-beleid'
      fullPath: '/ai-beleid'
      preLoaderRoute: typeof AiBeleidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-consultancy-mkb': {
      id: '/ai-consultancy-mkb'
      path: '/ai-consultancy-mkb'
      fullPath: '/ai-consultancy-mkb'
      preLoaderRoute: typeof AiConsultancyMkbRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-klantenservice-automatiseren': {
      id: '/ai-klantenservice-automatiseren'
      path: '/ai-klantenservice-automatiseren'
      fullPath: '/ai-klantenservice-automatiseren'
      preLoaderRoute: typeof AiKlantenserviceAutomatiserenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-lead-opvolging': {
      id: '/ai-lead-opvolging'
      path: '/ai-lead-opvolging'
      fullPath: '/ai-lead-opvolging'
      preLoaderRoute: typeof AiLeadOpvolgingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-project-vastgelopen': {
      id: '/ai-project-vastgelopen'
      path: '/ai-project-vastgelopen'
      fullPath: '/ai-project-vastgelopen'
      preLoaderRoute: typeof AiProjectVastgelopenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-scan': {
      id: '/ai-scan'
      path: '/ai-scan'
      fullPath: '/ai-scan'
      preLoaderRoute: typeof AiScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-voor-het-mkb-amsterdam': {
      id: '/ai-voor-het-mkb-amsterdam'
      path: '/ai-voor-het-mkb-amsterdam'
      fullPath: '/ai-voor-het-mkb-amsterdam'
      preLoaderRoute: typeof AiVoorHetMkbAmsterdamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/algemene-voorwaarden': {
      id: '/algemene-voorwaarden'
      path: '/algemene-voorwaarden'
      fullPath: '/algemene-voorwaarden'
      preLoaderRoute: typeof AlgemeneVoorwaardenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacyverklaring': {
      id: '/privacyverklaring'
      path: '/privacyverklaring'
      fullPath: '/privacyverklaring'
      preLoaderRoute: typeof PrivacyverklaringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tarieven': {
      id: '/tarieven'
      path: '/tarieven'
      fullPath: '/tarieven'
      preLoaderRoute: typeof TarievenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/whatsapp-follow-up-automatiseren': {
      id: '/whatsapp-follow-up-automatiseren'
      path: '/whatsapp-follow-up-automatiseren'
      fullPath: '/whatsapp-follow-up-automatiseren'
      preLoaderRoute: typeof WhatsappFollowUpAutomatiserenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/antwoorden': {
      id: '/_authenticated/antwoorden'
      path: '/antwoorden'
      fullPath: '/antwoorden'
      preLoaderRoute: typeof AuthenticatedAntwoordenRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/berichten': {
      id: '/_authenticated/berichten'
      path: '/berichten'
      fullPath: '/berichten'
      preLoaderRoute: typeof AuthenticatedBerichtenRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bezorgen': {
      id: '/_authenticated/bezorgen'
      path: '/bezorgen'
      fullPath: '/bezorgen'
      preLoaderRoute: typeof AuthenticatedBezorgenRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bezorglijst': {
      id: '/_authenticated/bezorglijst'
      path: '/bezorglijst'
      fullPath: '/bezorglijst'
      preLoaderRoute: typeof AuthenticatedBezorglijstRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/campagnes': {
      id: '/_authenticated/campagnes'
      path: '/campagnes'
      fullPath: '/campagnes'
      preLoaderRoute: typeof AuthenticatedCampagnesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contacten': {
      id: '/_authenticated/contacten'
      path: '/contacten'
      fullPath: '/contacten'
      preLoaderRoute: typeof AuthenticatedContactenRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/knowledge': {
      id: '/_authenticated/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof AuthenticatedKnowledgeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/support': {
      id: '/_authenticated/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof AuthenticatedSupportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/waarom-ai-pilots-mislukken': {
      id: '/blog/waarom-ai-pilots-mislukken'
      path: '/blog/waarom-ai-pilots-mislukken'
      fullPath: '/blog/waarom-ai-pilots-mislukken'
      preLoaderRoute: typeof BlogWaaromAiPilotsMislukkenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/embed/$slug': {
      id: '/embed/$slug'
      path: '/embed/$slug'
      fullPath: '/embed/$slug'
      preLoaderRoute: typeof EmbedSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/agents/$agentId': {
      id: '/_authenticated/agents/$agentId'
      path: '/agents/$agentId'
      fullPath: '/agents/$agentId'
      preLoaderRoute: typeof AuthenticatedAgentsAgentIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contact/$contactId': {
      id: '/_authenticated/contact/$contactId'
      path: '/contact/$contactId'
      fullPath: '/contact/$contactId'
      preLoaderRoute: typeof AuthenticatedContactContactIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRoute
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAntwoordenRoute: typeof AuthenticatedAntwoordenRoute
  AuthenticatedBerichtenRoute: typeof AuthenticatedBerichtenRoute
  AuthenticatedBezorgenRoute: typeof AuthenticatedBezorgenRoute
  AuthenticatedBezorglijstRoute: typeof AuthenticatedBezorglijstRoute
  AuthenticatedCampagnesRoute: typeof AuthenticatedCampagnesRoute
  AuthenticatedContactenRoute: typeof AuthenticatedContactenRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedKnowledgeRoute: typeof AuthenticatedKnowledgeRoute
  AuthenticatedSupportRoute: typeof AuthenticatedSupportRoute
  AuthenticatedAgentsAgentIdRoute: typeof AuthenticatedAgentsAgentIdRoute
  AuthenticatedContactContactIdRoute: typeof AuthenticatedContactContactIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAccountRoute: AuthenticatedAccountRoute,
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAntwoordenRoute: AuthenticatedAntwoordenRoute,
  AuthenticatedBerichtenRoute: AuthenticatedBerichtenRoute,
  AuthenticatedBezorgenRoute: AuthenticatedBezorgenRoute,
  AuthenticatedBezorglijstRoute: AuthenticatedBezorglijstRoute,
  AuthenticatedCampagnesRoute: AuthenticatedCampagnesRoute,
  AuthenticatedContactenRoute: AuthenticatedContactenRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedKnowledgeRoute: AuthenticatedKnowledgeRoute,
  AuthenticatedSupportRoute: AuthenticatedSupportRoute,
  AuthenticatedAgentsAgentIdRoute: AuthenticatedAgentsAgentIdRoute,
  AuthenticatedContactContactIdRoute: AuthenticatedContactContactIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AfmeldenRoute: AfmeldenRoute,
  AiAgentsAmsterdamRoute: AiAgentsAmsterdamRoute,
  AiAutomatiseringOpMaatRoute: AiAutomatiseringOpMaatRoute,
  AiBeleidRoute: AiBeleidRoute,
  AiConsultancyMkbRoute: AiConsultancyMkbRoute,
  AiKlantenserviceAutomatiserenRoute: AiKlantenserviceAutomatiserenRoute,
  AiLeadOpvolgingRoute: AiLeadOpvolgingRoute,
  AiProjectVastgelopenRoute: AiProjectVastgelopenRoute,
  AiScanRoute: AiScanRoute,
  AiVoorHetMkbAmsterdamRoute: AiVoorHetMkbAmsterdamRoute,
  AlgemeneVoorwaardenRoute: AlgemeneVoorwaardenRoute,
  AuthRoute: AuthRoute,
  PrivacyverklaringRoute: PrivacyverklaringRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TarievenRoute: TarievenRoute,
  WhatsappFollowUpAutomatiserenRoute: WhatsappFollowUpAutomatiserenRoute,
  BlogWaaromAiPilotsMislukkenRoute: BlogWaaromAiPilotsMislukkenRoute,
  EmbedSlugRoute: EmbedSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
