/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AiAgentsAmsterdamRouteImport } from './routes/ai-agents-amsterdam'
import { Route as AiKlantenserviceAutomatiserenRouteImport } from './routes/ai-klantenservice-automatiseren'
import { Route as AiLeadOpvolgingRouteImport } from './routes/ai-lead-opvolging'
import { Route as AiSalesAssistantRouteImport } from './routes/ai-sales-assistant'
import { Route as AiVoorMkbAmsterdamRouteImport } from './routes/ai-voor-mkb-amsterdam'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as OverOnsRouteImport } from './routes/over-ons'
import { Route as PrijzenRouteImport } from './routes/prijzen'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as WhatsappFollowUpAutomatiserenRouteImport } from './routes/whatsapp-follow-up-automatiseren'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated/account'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedKnowledgeRouteImport } from './routes/_authenticated/knowledge'
import { Route as AuthenticatedAgentsAgentIdRouteImport } from './routes/_authenticated/agents.$agentId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AiAgentsAmsterdamRoute = AiAgentsAmsterdamRouteImport.update({
  id: '/ai-agents-amsterdam',
  path: '/ai-agents-amsterdam',
  getParentRoute: () => rootRouteImport,
} as any)
const AiKlantenserviceAutomatiserenRoute =
  AiKlantenserviceAutomatiserenRouteImport.update({
    id: '/ai-klantenservice-automatiseren',
    path: '/ai-klantenservice-automatiseren',
    getParentRoute: () => rootRouteImport,
  } as any)
const AiLeadOpvolgingRoute = AiLeadOpvolgingRouteImport.update({
  id: '/ai-lead-opvolging',
  path: '/ai-lead-opvolging',
  getParentRoute: () => rootRouteImport,
} as any)
const AiSalesAssistantRoute = AiSalesAssistantRouteImport.update({
  id: '/ai-sales-assistant',
  path: '/ai-sales-assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const AiVoorMkbAmsterdamRoute = AiVoorMkbAmsterdamRouteImport.update({
  id: '/ai-voor-mkb-amsterdam',
  path: '/ai-voor-mkb-amsterdam',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const OverOnsRoute = OverOnsRouteImport.update({
  id: '/over-ons',
  path: '/over-ons',
  getParentRoute: () => rootRouteImport,
} as any)
const PrijzenRoute = PrijzenRouteImport.update({
  id: '/prijzen',
  path: '/prijzen',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const WhatsappFollowUpAutomatiserenRoute =
  WhatsappFollowUpAutomatiserenRouteImport.update({
    id: '/whatsapp-follow-up-automatiseren',
    path: '/whatsapp-follow-up-automatiseren',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedKnowledgeRoute = AuthenticatedKnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAgentsAgentIdRoute =
  AuthenticatedAgentsAgentIdRouteImport.update({
    id: '/agents/$agentId',
    path: '/agents/$agentId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-agents-amsterdam': typeof AiAgentsAmsterdamRoute
  '/ai-klantenservice-automatiseren': typeof AiKlantenserviceAutomatiserenRoute
  '/ai-lead-opvolging': typeof AiLeadOpvolgingRoute
  '/ai-sales-assistant': typeof AiSalesAssistantRoute
  '/ai-voor-mkb-amsterdam': typeof AiVoorMkbAmsterdamRoute
  '/auth': typeof AuthRoute
  '/over-ons': typeof OverOnsRoute
  '/prijzen': typeof PrijzenRoute
  '/reset-password': typeof ResetPasswordRoute
  '/whatsapp-follow-up-automatiseren': typeof WhatsappFollowUpAutomatiserenRoute
  '/account': typeof AuthenticatedAccountRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/knowledge': typeof AuthenticatedKnowledgeRoute
  '/agents/$agentId': typeof AuthenticatedAgentsAgentIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-agents-amsterdam': typeof AiAgentsAmsterdamRoute
  '/ai-klantenservice-automatiseren': typeof AiKlantenserviceAutomatiserenRoute
  '/ai-lead-opvolging': typeof AiLeadOpvolgingRoute
  '/ai-sales-assistant': typeof AiSalesAssistantRoute
  '/ai-voor-mkb-amsterdam': typeof AiVoorMkbAmsterdamRoute
  '/auth': typeof AuthRoute
  '/over-ons': typeof OverOnsRoute
  '/prijzen': typeof PrijzenRoute
  '/reset-password': typeof ResetPasswordRoute
  '/whatsapp-follow-up-automatiseren': typeof WhatsappFollowUpAutomatiserenRoute
  '/account': typeof AuthenticatedAccountRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/knowledge': typeof AuthenticatedKnowledgeRoute
  '/agents/$agentId': typeof AuthenticatedAgentsAgentIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/ai-agents-amsterdam': typeof AiAgentsAmsterdamRoute
  '/ai-klantenservice-automatiseren': typeof AiKlantenserviceAutomatiserenRoute
  '/ai-lead-opvolging': typeof AiLeadOpvolgingRoute
  '/ai-sales-assistant': typeof AiSalesAssistantRoute
  '/ai-voor-mkb-amsterdam': typeof AiVoorMkbAmsterdamRoute
  '/auth': typeof AuthRoute
  '/over-ons': typeof OverOnsRoute
  '/prijzen': typeof PrijzenRoute
  '/reset-password': typeof ResetPasswordRoute
  '/whatsapp-follow-up-automatiseren': typeof WhatsappFollowUpAutomatiserenRoute
  '/_authenticated/account': typeof AuthenticatedAccountRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/knowledge': typeof AuthenticatedKnowledgeRoute
  '/_authenticated/agents/$agentId': typeof AuthenticatedAgentsAgentIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-agents-amsterdam'
    | '/ai-klantenservice-automatiseren'
    | '/ai-lead-opvolging'
    | '/ai-sales-assistant'
    | '/ai-voor-mkb-amsterdam'
    | '/auth'
    | '/over-ons'
    | '/prijzen'
    | '/reset-password'
    | '/whatsapp-follow-up-automatiseren'
    | '/account'
    | '/admin'
    | '/dashboard'
    | '/knowledge'
    | '/agents/$agentId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-agents-amsterdam'
    | '/ai-klantenservice-automatiseren'
    | '/ai-lead-opvolging'
    | '/ai-sales-assistant'
    | '/ai-voor-mkb-amsterdam'
    | '/auth'
    | '/over-ons'
    | '/prijzen'
    | '/reset-password'
    | '/whatsapp-follow-up-automatiseren'
    | '/account'
    | '/admin'
    | '/dashboard'
    | '/knowledge'
    | '/agents/$agentId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/ai-agents-amsterdam'
    | '/ai-klantenservice-automatiseren'
    | '/ai-lead-opvolging'
    | '/ai-sales-assistant'
    | '/ai-voor-mkb-amsterdam'
    | '/auth'
    | '/over-ons'
    | '/prijzen'
    | '/reset-password'
    | '/whatsapp-follow-up-automatiseren'
    | '/_authenticated/account'
    | '/_authenticated/admin'
    | '/_authenticated/dashboard'
    | '/_authenticated/knowledge'
    | '/_authenticated/agents/$agentId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AiAgentsAmsterdamRoute: typeof AiAgentsAmsterdamRoute
  AiKlantenserviceAutomatiserenRoute: typeof AiKlantenserviceAutomatiserenRoute
  AiLeadOpvolgingRoute: typeof AiLeadOpvolgingRoute
  AiSalesAssistantRoute: typeof AiSalesAssistantRoute
  AiVoorMkbAmsterdamRoute: typeof AiVoorMkbAmsterdamRoute
  AuthRoute: typeof AuthRoute
  OverOnsRoute: typeof OverOnsRoute
  PrijzenRoute: typeof PrijzenRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  WhatsappFollowUpAutomatiserenRoute: typeof WhatsappFollowUpAutomatiserenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-agents-amsterdam': {
      id: '/ai-agents-amsterdam'
      path: '/ai-agents-amsterdam'
      fullPath: '/ai-agents-amsterdam'
      preLoaderRoute: typeof AiAgentsAmsterdamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-klantenservice-automatiseren': {
      id: '/ai-klantenservice-automatiseren'
      path: '/ai-klantenservice-automatiseren'
      fullPath: '/ai-klantenservice-automatiseren'
      preLoaderRoute: typeof AiKlantenserviceAutomatiserenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-lead-opvolging': {
      id: '/ai-lead-opvolging'
      path: '/ai-lead-opvolging'
      fullPath: '/ai-lead-opvolging'
      preLoaderRoute: typeof AiLeadOpvolgingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-sales-assistant': {
      id: '/ai-sales-assistant'
      path: '/ai-sales-assistant'
      fullPath: '/ai-sales-assistant'
      preLoaderRoute: typeof AiSalesAssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-voor-mkb-amsterdam': {
      id: '/ai-voor-mkb-amsterdam'
      path: '/ai-voor-mkb-amsterdam'
      fullPath: '/ai-voor-mkb-amsterdam'
      preLoaderRoute: typeof AiVoorMkbAmsterdamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/over-ons': {
      id: '/over-ons'
      path: '/over-ons'
      fullPath: '/over-ons'
      preLoaderRoute: typeof OverOnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prijzen': {
      id: '/prijzen'
      path: '/prijzen'
      fullPath: '/prijzen'
      preLoaderRoute: typeof PrijzenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/whatsapp-follow-up-automatiseren': {
      id: '/whatsapp-follow-up-automatiseren'
      path: '/whatsapp-follow-up-automatiseren'
      fullPath: '/whatsapp-follow-up-automatiseren'
      preLoaderRoute: typeof WhatsappFollowUpAutomatiserenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/knowledge': {
      id: '/_authenticated/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof AuthenticatedKnowledgeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/agents/$agentId': {
      id: '/_authenticated/agents/$agentId'
      path: '/agents/$agentId'
      fullPath: '/agents/$agentId'
      preLoaderRoute: typeof AuthenticatedAgentsAgentIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRoute
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedKnowledgeRoute: typeof AuthenticatedKnowledgeRoute
  AuthenticatedAgentsAgentIdRoute: typeof AuthenticatedAgentsAgentIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAccountRoute: AuthenticatedAccountRoute,
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedKnowledgeRoute: AuthenticatedKnowledgeRoute,
  AuthenticatedAgentsAgentIdRoute: AuthenticatedAgentsAgentIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AiAgentsAmsterdamRoute: AiAgentsAmsterdamRoute,
  AiKlantenserviceAutomatiserenRoute: AiKlantenserviceAutomatiserenRoute,
  AiLeadOpvolgingRoute: AiLeadOpvolgingRoute,
  AiSalesAssistantRoute: AiSalesAssistantRoute,
  AiVoorMkbAmsterdamRoute: AiVoorMkbAmsterdamRoute,
  AuthRoute: AuthRoute,
  OverOnsRoute: OverOnsRoute,
  PrijzenRoute: PrijzenRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  WhatsappFollowUpAutomatiserenRoute: WhatsappFollowUpAutomatiserenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
